#!/usr/bin/env python3
"""Generate pre-rotated aircraft icon bitmaps for the radar UI.

Run: /opt/hermes/.venv/bin/python3 scripts/gen_aircraft_icon.py

Writes:
  include/ui/aircraft_icon_data.h       generated, committed
  src/ui/aircraft_icon_data.cpp         generated, committed
  .artifacts/aircraft_icon_preview.png  visual check only, gitignored
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

ICON_PX = 19          # square icon bounding box, pixels
ROTATIONS = 72        # one every 5 degrees
SUPERSAMPLE = 8       # rasterise at ICON_PX * SUPERSAMPLE, then downscale
BYTES_PER_ROW = (ICON_PX + 1) // 2      # 4bpp: two pixels per byte
BYTES_PER_ROT = BYTES_PER_ROW * ICON_PX

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "include" / "ui" / "aircraft_icon_data.h"
OUT_CPP = ROOT / "src" / "ui" / "aircraft_icon_data.cpp"
PREVIEW = ROOT / ".artifacts" / "aircraft_icon_preview.png"

# Top-down silhouette, nose at +Y. Unit box: 1.0 = half the icon edge.
# Geometry approved via the preview renders (2026-09-28). No FIN polygon:
# a top-down fin is seen edge-on and disappears inside the fuselage.
FUSELAGE = [(0.00, 1.00), (0.12, 0.15), (0.10, -0.60),
            (0.00, -1.00), (-0.10, -0.60), (-0.12, 0.15)]
# Wing, 5 points: long root chord at the body, tapering to a thin tip.
# root LE -> leading-edge kink -> tip LE -> tip TE -> root TE
WING_R = [(0.10, 0.30), (0.58, -0.02), (1.00, -0.42), (0.98, -0.54), (0.10, -0.08)]
WING_L = [(-x, y) for x, y in WING_R]
TAIL_R = [(0.08, -0.58), (0.50, -0.86), (0.47, -0.96), (0.08, -0.80)]
TAIL_L = [(-x, y) for x, y in TAIL_R]

POLYGONS = [FUSELAGE, WING_R, WING_L, TAIL_R, TAIL_L]

# TUNING THE WING: only WING_R's 2nd and 3rd numbers change the root thickness.
#   leve  (light)   [(0.10, 0.24), (0.60,  0.02), (1.00, -0.42), (0.98, -0.54), (0.10, -0.04)]
#   media (current) [(0.10, 0.30), (0.58, -0.02), (1.00, -0.42), (0.98, -0.54), (0.10, -0.08)]
#   forte (strong)  [(0.10, 0.36), (0.55, -0.04), (1.00, -0.42), (0.98, -0.54), (0.10, -0.12)]
# Changing the wing changes NO constant -- no ICON_PX, no byte counts, nothing in
# the firmware. It only changes generated data. Rerun Tasks 2-4 after editing.

HEADER_TMPL = """\
// Generated by scripts/gen_aircraft_icon.py -- do not edit.
#pragma once

#include <cstdint>

namespace data::aircraft_icon {{

/** Square icon bounding box, pixels. */
constexpr int kSize = {size};
/** Pre-rendered rotations; index i is i * (360 / kRotations) degrees. */
constexpr int kRotations = {rotations};
/** Bytes per rotation: 4bpp, {bytes_per_row} bytes per {size}px row, high nibble first. */
constexpr int kBytesPerRotation = {bytes_per_rot};
/** Palette index treated as transparent by pushImage. */
constexpr int kTransparentIndex = 0;

/** kRotations * kBytesPerRotation bytes, rotation-major. */
extern const uint8_t kIcon[];

}}  // namespace data::aircraft_icon
"""


def render_base() -> Image.Image:
    """Rasterise the silhouette once, nose up, at SUPERSAMPLE resolution."""
    size = ICON_PX * SUPERSAMPLE
    img = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(img)
    for poly in POLYGONS:
        pts = [((x + 1.0) * 0.5 * (size - 1),
                (1.0 - y) * 0.5 * (size - 1)) for x, y in poly]
        draw.polygon(pts, fill=255)
    return img


def rotation_alpha(base: Image.Image, heading_deg: float) -> list[int]:
    """Coverage (0..15) per pixel for one heading; heading grows clockwise, 0 = north."""
    # PIL rotates counter-clockwise for positive angles, hence the negation.
    rot = base.rotate(-heading_deg, resample=Image.BICUBIC, fillcolor=0)
    small = rot.resize((ICON_PX, ICON_PX), Image.LANCZOS)
    return [min(15, (v * 15 + 127) // 255) for v in small.tobytes()]


def pack4bpp(alpha: list[int]) -> bytes:
    out = bytearray()
    for row in range(ICON_PX):
        start = row * ICON_PX
        for col in range(0, ICON_PX, 2):
            hi = alpha[start + col]
            lo = alpha[start + col + 1] if col + 1 < ICON_PX else 0
            out.append((hi << 4) | lo)
    return bytes(out)


def build() -> bytes:
    base = render_base()
    blob = bytearray()
    for i in range(ROTATIONS):
        blob += pack4bpp(rotation_alpha(base, i * 360.0 / ROTATIONS))
    return bytes(blob)


def render_cpp(blob: bytes) -> str:
    lines = [
        "// Generated by scripts/gen_aircraft_icon.py -- do not edit.",
        '#include "ui/aircraft_icon_data.h"',
        "",
        "namespace data::aircraft_icon {",
        "",
        "const uint8_t kIcon[] = {",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    lines += [
        "};",
        "",
        "static_assert(sizeof(kIcon) == kRotations * kBytesPerRotation,",
        '              "aircraft icon data size mismatch");',
        "",
        "}  // namespace data::aircraft_icon",
        "",
    ]
    return "\n".join(lines)


def write_preview(base: Image.Image, out_path: Path) -> None:
    """Tile every rotation into one PNG so the shape can be eyeballed before flashing."""
    cell = ICON_PX + 2
    cols = 12
    rows = (ROTATIONS + cols - 1) // cols
    canvas = Image.new("RGB", (cols * cell, rows * cell), (4, 10, 28))
    for i in range(ROTATIONS):
        small = base.rotate(-i * 360.0 / ROTATIONS,
                            resample=Image.BICUBIC, fillcolor=0)
        small = small.resize((ICON_PX, ICON_PX), Image.LANCZOS)
        px = small.load()
        tile = Image.new("RGB", (ICON_PX, ICON_PX), (4, 10, 28))
        tpx = tile.load()
        for y in range(ICON_PX):
            for x in range(ICON_PX):
                a = px[x, y] / 255.0
                tpx[x, y] = (int(250 * a + 4 * (1 - a)),
                             int(204 * a + 10 * (1 - a)),
                             int(60 * a + 28 * (1 - a)))
        canvas.paste(tile, ((i % cols) * cell + 1, (i // cols) * cell + 1))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def main() -> int:
    base = render_base()
    blob = build()

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_CPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(
        HEADER_TMPL.format(size=ICON_PX, rotations=ROTATIONS,
                           bytes_per_row=BYTES_PER_ROW,
                           bytes_per_rot=BYTES_PER_ROT),
        encoding="utf-8")
    OUT_CPP.write_text(render_cpp(blob), encoding="utf-8")
    write_preview(base, PREVIEW)

    print(f"wrote {OUT_H.relative_to(ROOT)} + {OUT_CPP.relative_to(ROOT)} "
          f"({len(blob)} bytes, {ROTATIONS} rotations)")
    print(f"preview: {PREVIEW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
