// Generated by scripts/gen_aircraft_icon.py -- do not edit.
#pragma once

#include <cstdint>

namespace data::aircraft_icon {

/** Square icon bounding box, pixels. */
constexpr int kSize = 19;
/** Pre-rendered rotations; index i is i * (360 / kRotations) degrees. */
constexpr int kRotations = 72;
/** Bytes per rotation: 4bpp, 10 bytes per 19px row, high nibble first. */
constexpr int kBytesPerRotation = 190;
/** Palette index treated as transparent by pushImage. */
constexpr int kTransparentIndex = 0;

/** kRotations * kBytesPerRotation bytes, rotation-major. */
extern const uint8_t kIcon[];

}  // namespace data::aircraft_icon

namespace data::aircraft_icon_small {

/** Square icon bounding box, pixels. */
constexpr int kSize = 13;
/** Pre-rendered rotations; index i is i * (360 / kRotations) degrees. */
constexpr int kRotations = 72;
/** Bytes per rotation: 4bpp, 7 bytes per 13px row, high nibble first. */
constexpr int kBytesPerRotation = 91;
/** Palette index treated as transparent by pushImage. */
constexpr int kTransparentIndex = 0;

/** kRotations * kBytesPerRotation bytes, rotation-major. */
extern const uint8_t kIcon[];

}  // namespace data::aircraft_icon_small
